# Generated by Django 3.2.2 on 2021-05-16 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('hasPhone', models.BooleanField()),
                ('phoneNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid form. Up to 15 digits.', regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
