# Generated by Django 3.2.2 on 2021-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
