# Generated by Django 3.2.2 on 2021-05-28 13:45

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_usercard_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_path),
        ),
    ]
