# Generated by Django 3.2.2 on 2021-05-28 14:03

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_usercard_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='usercard',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.image'),
        ),
    ]
