# Generated by Django 3.2.2 on 2021-05-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210528_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='files',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.usercard'),
        ),
    ]
