# Generated by Django 3.2.2 on 2021-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210528_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='testBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
    ]
