# Generated by Django 3.2.2 on 2021-06-22 12:58

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_testbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='testBase',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='files',
        ),
        migrations.AddField(
            model_name='userimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.usercard'),
        ),
    ]
