# Generated by Django 3.2.2 on 2021-06-22 15:30

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210622_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_path),
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
