# Generated by Django 3.2.2 on 2021-06-23 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210622_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid form. Up to 15 digits.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
