# Generated by Django 3.2.2 on 2021-06-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_usercard_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
